modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="compactstorage"
version="${file.jarVersion}"
displayName="Compact Storage"
updateJSONURL="http://myurl.me/"
displayURL="http://tobystrong.me/compactstorage/"
logoFile="compactstorage.png"
credits="Thanks for this example mod goes to Java"
authors="Toby Strong"
description='''
Bringing chests and backpacks of all sizes right to your Minecraft world
'''
[[dependencies.compactstorage]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.compactstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
